version: '3.1'



services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    healthcheck:
      test: "exit 0"

  sanic:    
    build: ./sanic
    ports:
      - 8000:8000
    
    volumes:
      - ./sanic:/code
    links:
      - "pg_db:db"
    
    depends_on:
      pg_db:
        condition: service_healthy
    command: >
      bash -c "./init_database_table.sh 
      && python ./main.py"
    


